### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Shai",
  "email": "sahi@example.com",
  "password": "passwordsahi123"
}

### Invalid Registration
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "",
  "email": "wrong-email",
  "password": "123"
}


### Login User
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "sahi@example.com",
  "password": "passwordsahi123"
}

### Invalid Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "hello",
  "password": ""
}

### Get My Tasks
GET http://localhost:5000/api/tasks

### Get task
GET http://localhost:5000/api/tasks/6a8a9aa9f5df857152497853

### Invalid Task ID
GET http://localhost:5000/api/tasks/hello

### Create Task
POST http://localhost:5000/api/tasks
Content-Type: application/json

{
    "title": "Learn React",
  "description": "Build the frontend",
  "status": "pending",
  "priority": "high"
}

### Invalid Task
POST http://localhost:5000/api/tasks
Content-Type: application/json

{
  "title": "A",
  "status": "finished",
  "priority": "very-high"
}

### Logout
POST http://localhost:5000/api/auth/logout

### Admin Users
GET http://localhost:5000/api/admin/users

### Update Task
PUT http://localhost:5000/api/tasks/6a8a9903f5df857152497840
Content-Type: application/json

{
  "title": "Learn React + Tailwind",
  "description": "Build the frontend using React and Tailwind CSS",
  "status": "in-progress",
  "priority": "high"
}

### Delete Task
DELETE http://localhost:5000/api/tasks/6a8aa88c6440bd7b43ab5a5c