### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Shai",
  "email": "sahi@example.com",
  "password": "passwordsahi123"
}


### Login User
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "ranjitha@example.com",
  "password": "password123"
}


### Get My Tasks
GET http://localhost:5000/api/tasks


### Create Task
POST http://localhost:5000/api/tasks
Content-Type: application/json

{
  "title": "Learn CPP",
  "description": "Build the complete CPP code",
  "status": "pending",
  "priority": "medium"
}


### Logout
POST http://localhost:5000/api/auth/logout